apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: tawy9wkew-nodejs 
  janus-idp.io/tekton: tawy9wkew-nodejs
  backstage.io/kubernetes-id: tawy9wkew-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tawy9wkew-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml