apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: tawy9wkew-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tawy9wkew-nodejs 
  name: tawy9wkew-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: tawy9wkew-nodejs 
